name: Build & Push notification-service
on:
  workflow_dispatch:
  push:
    branches: ['**']
    paths:
      - 'transfa-backend/notification-service/**'
      - '.github/workflows/notification-service-ecr.yml'
  pull_request:
    branches: ['**']
    paths:
      - 'transfa-backend/notification-service/**'
      - '.github/workflows/notification-service-ecr.yml'

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    concurrency:
      group: ecr-notification-service-${{ github.ref }}
      cancel-in-progress: false
    env:
      ECR_REGISTRY: ${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
      ECR_REPOSITORY: transfa/notification-service
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Debug context
        run: |
          echo "Actor: $GITHUB_ACTOR"
          echo "Ref: $GITHUB_REF"
          echo "Event: $GITHUB_EVENT_NAME"

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.ECR_ACCOUNT_ID }}

      - name: Build Docker image
        working-directory: transfa-backend/notification-service
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
